language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="cmake gobject-introspection libgee-0.8-dev libgirepository1.0-dev libgtk-3-dev valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && env CTEST_OUTPUT_ON_FAILURE=true make"

script:
 - echo BUILDS PASSED
