.TH granite-demo 1 "Jun 09, 2012"
.SH NAME
granite-demo \- small demo application to show Granite Widgets
.PP
\fBgranite-demo\fP is a small demo application to show Granite Widgets.
Granite is an extension of GTK+. Among other things, it provides
complex widgets and convenience functions designed for use in apps
built for elementary OS.
.SH AUTHOR
granite was written by Maxwell Barvian <mbarvian@gmail.com>, Daniel Foré
<bunny@go-docky.com>, Avi Romanoff <aviromanoff@gmail.com>.
.PP
This manual page was written by Devid Antonio Filoni <d.filoni@ubuntu.com>,
for the Debian project (but may be used by others).
